# Generated by Django 2.2 on 2020-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200307_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='number',
        ),
        migrations.AddField(
            model_name='clue',
            name='code',
            field=models.CharField(max_length=30, null=True, verbose_name='code'),
        ),
    ]
