# Generated by Django 2.2 on 2020-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200308_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='paragraph1',
            field=models.TextField(null=True, verbose_name='paragraph1'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='paragraph2',
            field=models.TextField(null=True, verbose_name='paragraph2'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='paragraph3',
            field=models.TextField(null=True, verbose_name='paragraph3'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='paragraph4',
            field=models.TextField(null=True, verbose_name='paragraph4'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='paragraph5',
            field=models.TextField(null=True, verbose_name='paragraph5'),
        ),
    ]
