# Generated by Django 2.2 on 2020-03-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200308_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='paragraph2',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='paragraph3',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='paragraph4',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='paragraph5',
        ),
    ]
