# Generated by Django 2.2 on 2020-03-18 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200312_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclues',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 18, 18, 0, 6, 896930)),
        ),
    ]
