# Generated by Django 2.2 on 2020-03-18 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_userclues_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='paragraph1',
            field=models.TextField(null=True, verbose_name='paragraph1'),
        ),
        migrations.AlterField(
            model_name='userclues',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 18, 18, 13, 49, 214300)),
        ),
    ]
