# Generated by Django 2.2 on 2020-03-18 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200318_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='paragraph1',
            field=models.TextField(blank=True, null=True, verbose_name='paragraph1'),
        ),
        migrations.AlterField(
            model_name='userclues',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 18, 18, 16, 23, 940686)),
        ),
    ]
