# Generated by Django 2.2 on 2021-10-28 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200320_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='optional_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='réponse optionelle'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='optional_question',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='question optionelle'),
        ),
        migrations.AlterField(
            model_name='userclues',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 22, 32, 32, 279646)),
        ),
    ]
