# Generated by Django 2.2 on 2021-10-28 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211028_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclues',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 22, 33, 17, 308529)),
        ),
    ]
