# Generated by Django 2.2 on 2021-12-22 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20211028_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclues',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 22, 21, 28, 59, 917210)),
        ),
    ]
