# Generated by Django 2.2 on 2021-12-22 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20211222_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclues',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 22, 21, 29, 19, 295149)),
        ),
    ]
