# Generated by Django 4.1 on 2022-08-20 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_userclues_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclues',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 20, 20, 5, 50, 603702)),
        ),
    ]
